linears_dh::Double_linked_list
using linears_dh::Double_linked_list< _Ty >::__pointer_t = dbl_node<_Ty>*
using linears_dh::Double_linked_list< _Ty >::__const_pointer_t = const dbl_node<_Ty>*
using linears_dh::Double_linked_list< _Ty >::pointer_type = std::shared_ptr<Double_linked_list<_Ty>>
using linears_dh::Double_linked_list< _Ty >::const_pointer_type = const std::shared_ptr<Double_linked_list<_Ty>>
friend class iterator
__pointer_t linears_dh::Double_linked_list< _Ty >::_head
Referenced by linears_dh::Double_linked_list< _Ty >::Double_linked_list, linears_dh::Double_linked_list< _Ty >::push_back, linears_dh::Double_linked_list< _Ty >::~Double_linked_list.
__pointer_t linears_dh::Double_linked_list< _Ty >::_tail
Referenced by linears_dh::Double_linked_list< _Ty >::push_back, linears_dh::Double_linked_list< _Ty >::~Double_linked_list.
unsigned linears_dh::Double_linked_list< _Ty >::_size
Referenced by linears_dh::Double_linked_list< _Ty >::push_back.
iterator linears_dh::Double_linked_list< _Ty >::begin() const
Referenced by linears_dh::Double_linked_list< _Ty >::Double_linked_list.
iterator linears_dh::Double_linked_list< _Ty >::end() const
Referenced by linears_dh::Double_linked_list< _Ty >::Double_linked_list.
linears_dh::Double_linked_list< _Ty >::Double_linked_list()
linears_dh::Double_linked_list< _Ty >::Double_linked_list(const iterator &beginning, const iterator &ending)
linears_dh::Double_linked_list< _Ty >::Double_linked_list(const Double_linked_list &lst)
References linears_dh::Double_linked_list< _Ty >::_head, linears_dh::Double_linked_list< _Ty >::begin, linears_dh::dbl_node< Ty >::data, linears_dh::Double_linked_list< _Ty >::end, linears_dh::dbl_node< Ty >::next.
linears_dh::Double_linked_list< _Ty >::~Double_linked_list()
References linears_dh::Double_linked_list< _Ty >::_head, linears_dh::Double_linked_list< _Ty >::_tail, linears_dh::dbl_node< Ty >::next.
constexpr size_t linears_dh::Double_linked_list< _Ty >::size() const
constexpr bool linears_dh::Double_linked_list< _Ty >::is_empty() const
Referenced by linears_dh::Double_linked_list< _Ty >::push_back.
void linears_dh::Double_linked_list< _Ty >::push_back(_Ty val)
References linears_dh::Double_linked_list< _Ty >::_head, linears_dh::Double_linked_list< _Ty >::_size, linears_dh::Double_linked_list< _Ty >::_tail, linears_dh::Double_linked_list< _Ty >::is_empty, linears_dh::dbl_node< Ty >::next, linears_dh::dbl_node< Ty >::prev.
Referenced by BOOST_AUTO_TEST_CASE.